# Generated by Django 3.0.2 on 2020-02-22 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='trouble')),
            ],
            options={
                'verbose_name': 'Alarm Type',
                'verbose_name_plural': 'Alarm Types',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=3, verbose_name='Block')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Model')),
                ('description', models.TextField(verbose_name='Description')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial number')),
                ('manual', models.FileField(upload_to='manual/', verbose_name='Manual')),
                ('inventory_number', models.CharField(max_length=20, unique=True, verbose_name='Inventory number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Equipment type')),
                ('name', models.CharField(default='Refrigirator', max_length=150, verbose_name='Type of equipment')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=2, verbose_name='Floor')),
                ('room', models.CharField(max_length=6, verbose_name='Room')),
                ('department', models.CharField(blank=True, max_length=64, null=True, verbose_name='Departament')),
                ('room_type', models.CharField(blank=True, max_length=32, null=True)),
                ('gases', models.CharField(blank=True, default='None', max_length=64, null=True)),
                ('block', models.ForeignKey(max_length=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Block', verbose_name='Block')),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site', models.URLField(blank=True, max_length=32, null=True, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('temp1', models.FloatField(verbose_name='Temp-1')),
                ('temp2', models.FloatField(verbose_name='Temp-2')),
                ('temp3', models.FloatField(verbose_name='Temp-3')),
                ('leak1', models.BooleanField(default=False, verbose_name='Leak-1')),
                ('leak2', models.BooleanField(default=False, verbose_name='Leak-2')),
                ('leak3', models.BooleanField(default=False, verbose_name='Leak-3')),
                ('date_of_installation', models.DateField(default=datetime.date.today, verbose_name='Date of installation')),
                ('date_of_last_service', models.DateField(default=datetime.date.today, verbose_name='Date of last service')),
                ('inventory_number', models.CharField(max_length=20, verbose_name='Inventory nimber')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='Equipment')),
                ('lab', models.ManyToManyField(to='equipment.Laboratory', verbose_name='Laboratory')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('position', models.CharField(max_length=150, verbose_name='Position')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('office', models.CharField(max_length=6, verbose_name='Office')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone')),
                ('work_phone', models.CharField(max_length=8, verbose_name='Work phone')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Responsible Person',
                'verbose_name_plural': 'Responsible Persons',
            },
        ),
        migrations.CreateModel(
            name='TechnicalContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('position', models.CharField(max_length=150, verbose_name='Position')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('office', models.CharField(max_length=6, verbose_name='Office')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone')),
                ('work_phone', models.CharField(max_length=8, verbose_name='Work phone')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Technical Contact',
                'verbose_name_plural': 'Technical Contacts',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_service', models.DateField(default=datetime.date.today, verbose_name='last service')),
                ('next_service', models.DateField(help_text='Please use following format: <em>YYYY-MM-DD</em>.', verbose_name='Next service')),
                ('spares', models.CharField(max_length=150, verbose_name='Spares')),
                ('what_is_done', models.TextField(verbose_name='What is done')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('mailWasSent', models.BooleanField(default=False, verbose_name='Inform')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Node', verbose_name='Node')),
                ('type', models.ManyToManyField(to='equipment.AlarmType', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='responsible_person',
            field=models.ManyToManyField(to='equipment.ResponsiblePerson', verbose_name='Responsible Person'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='technical_contact',
            field=models.ManyToManyField(to='equipment.TechnicalContact', verbose_name='Technical Contact'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_of_equipment',
            field=models.ManyToManyField(to='equipment.EquipmentType', verbose_name='Type of equipment'),
        ),
    ]
