# Generated by Django 3.0.2 on 2020-01-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='id',
        ),
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='department',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Departament'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='gases',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='room_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='site',
            field=models.URLField(blank=True, max_length=32, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='room',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Room'),
        ),
    ]
